Ndarrays, Indexing, and Slicing

In [2]:
#Start by importing the numpy and pandas library

import numpy as np
import pandas as pd

#Try creating a 4 row x 4 column array of integers
int_ar1 = np.arange(1,17).reshape(4,4)
int_ar1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [3]:
np.ones([4,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
#let's try altering this array. First, let's save a sopy of this array
int_ar2 = int_ar1.copy()

In [14]:
#Next, let's change the entire first row to twos (2)
int_ar2[0, 0:4] = 2
int_ar2

array([[ 2,  2,  2,  2],
       [ 4, 19,  6,  7],
       [ 8,  9, 19, 11],
       [12, 13, 14, 19]])

In [15]:
#With some for loops, we can more dynamically change our arrays. 
# Change the diagonal to a new number.
np.fill_diagonal(int_ar2, 20)

# for x in range(4):
#     int_ar2[x][x] = 10
# int_ar2

In [16]:
int_ar2

array([[20,  2,  2,  2],
       [ 4, 20,  6,  7],
       [ 8,  9, 20, 11],
       [12, 13, 14, 20]])

In [17]:
#We can also change the contents of an array through arithmetic procedures.
# Multiply the values by some number.
int_ar2 = int_ar2*2
int_ar2

array([[40,  4,  4,  4],
       [ 8, 40, 12, 14],
       [16, 18, 40, 22],
       [24, 26, 28, 40]])

In [10]:
# Subtract some number
int_ar2 = int_ar2-1
int_ar2

array([[19,  1,  1,  1],
       [ 4, 19,  6,  7],
       [ 8,  9, 19, 11],
       [12, 13, 14, 19]])

Arrays and Matrices

In [31]:
#Confirm that the array is 4x4
#Remembers, arrays are given by ----> # of rows X # of columns.
int_ar2.shape

(4, 4)

In [32]:
#Okay, now try and create a 5 x 5 array of ones
np.ones([5,5])


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
#Create 3 identity matrices of any size

In [35]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## Quick List Comprehension/Lambda function Exercises

In [11]:
# 1
# make a list comprehension which filters the even numbers 
#out of the following numpy array: np.arange(1,100,3)

In [40]:
evens = [x for x in np.arange(1,100,3) if not(x%2)]
evens

[4, 10, 16, 22, 28, 34, 40, 46, 52, 58, 64, 70, 76, 82, 88, 94]

In [1]:
# 2 for the following mispelled list of Beatles, write a function correct_beatles,
# then use the built-in map function to create a corrected list of Beatles.

beatle_list = ['John', 'Rango', 'Pal', 'Geoge', 'george'
               'Rungo', 'Gage', 'Pul', 'Jonathan', 'Mike']

def correct_beatles(name):
    
    the_beatles = {'j':'John', 'p':'Paul', 
                   'g':'George','r':'Ringo'}
        
    if name in the_beatles.values():
        return name.capitalize()
    
    elif name[0].lower() not in the_beatles.keys():
        return f"{name} is not in the Beatles!"
    
    else:
        return the_beatles[name[0].lower()]


correct_beatles('Rango')
        
    
correct_list = map(correct_beatles, beatle_list)
print(list(correct_list))

['John', 'Ringo', 'Paul', 'George', 'George', 'George', 'Paul', 'John', 'Mike is not in the Beatles!']
